// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo0ou2FW5M8CNFOBAaLA27pYywlcGi42o',
    appId: '1:760280015085:web:b29fdd00e0d34286fc2ce4',
    messagingSenderId: '760280015085',
    projectId: 'sample-irf',
    authDomain: 'sample-irf.firebaseapp.com',
    storageBucket: 'sample-irf.appspot.com',
    measurementId: 'G-PXC8N065YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebSzrweaeCbgLBQdJzICprEmlwpx2PQw',
    appId: '1:760280015085:android:67344a26946bd712fc2ce4',
    messagingSenderId: '760280015085',
    projectId: 'sample-irf',
    storageBucket: 'sample-irf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIdqb45gIzPvm18IEZSyfNlFqE1q7fSHY',
    appId: '1:760280015085:ios:b87585048024b575fc2ce4',
    messagingSenderId: '760280015085',
    projectId: 'sample-irf',
    storageBucket: 'sample-irf.appspot.com',
    iosClientId: '760280015085-6r4kee617mm0u5jf62k19b677c3qrvs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.indianRaceFantasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIdqb45gIzPvm18IEZSyfNlFqE1q7fSHY',
    appId: '1:760280015085:ios:c827c4a6f22dc521fc2ce4',
    messagingSenderId: '760280015085',
    projectId: 'sample-irf',
    storageBucket: 'sample-irf.appspot.com',
    iosClientId: '760280015085-ujrp90p3478s376c0ihq320atak7she5.apps.googleusercontent.com',
    iosBundleId: 'com.example.indianRaceFantasy.RunnerTests',
  );
}
